[package]
name = "mlp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.1"
nalgebra = "0.33.2"
rand_distr = "0.5.1"
image = "0.25.6"
bytemuck = "1.23.0"
tempfile = "3.20.0"